name: News Parser Automation

on:
  pull_request:
    paths:
      - "scripts/input.json"
  push:
    branches:
      - main
    paths:
      - "scripts/input.json"

permissions:
  contents: write

jobs:
  run-parser:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install
        working-directory: ./scripts

      - name: Run news parser
        run: yarn start
        working-directory: ./scripts

      - name: Install dependencies
        run: yarn install
        working-directory: ./

      - name: buid stock-news
        run: yarn build
        working-directory: ./

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update newsData.json with new parsed data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
